### ISSUE TITLE
Any way to make it work in Web browser with Flash?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [tuarua/BitTorrentANE#3]
If it's possible so I can work on it.

**Comment by tuarua** [comment]
No - ANEs don't work in Flash Player - only in AIR.
This ANE uses the bittorrent protocol and is written in C++, and uses libtorrent.

Flash player has had it's own P2P implementation since 10.1
The protocol is called rtmfp. It connects Flash player clients over P2P.
http://www.adobe.com/products/adobe-media-server-extended/rtmfp-faq.html

webtorrent is not bittorrent which is a different protocol altogether.

**Comment by ROBERT-MCDOWELL** [comment]
Yes I know, I mean do you need any system dependencies to use libtorrent?
if not so the C++ code can be compiled at the top of a swf with flasCC/crossbridge...
I though webtorrent was torrent compatible...

**Comment by tuarua** [comment]
Libtorrent also uses openSSL,, the thread, chronos, system libs from boost.
You are free to give it a go - to compile using flasCC/crossbridge. 
Even after this you may hit problems connecting through the default bittorrent ports. I doubt a browser plugin would be allowed to use these. FP has no direct access to the file system so a file would be saved and seeded from memory.
I am not willing to spend time trying to bring this to flash player given the EOL in 2020.

You can only use webtorrent to communicate with bittorrent when it's built as a hybrid Desktop app.

From the official WebTorrent site.
> In the browser, WebTorrent can only download torrents that are seeded by a WebRTC-capable torrent client.

**Comment by ROBERT-MCDOWELL** [comment]
> flash player given the EOL in 2020
a lot of surprises can happen in 3 years, this is the beauty of open source....
webRTC is only sockets working with browsers right?
anyhow, it's just too obvious that there is nothing innocent in all what's happening with flash,webrtc, google,adobe... not really fancy...

**Comment by ROBERT-MCDOWELL** [comment]
Sorry to comment again Tuarua, do you know if there are some project created
that convert AS to web assembly? do you know if Air app with ANE will be able to convert in WASM?
